# Generated by Django 5.1.1 on 2026-06-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0002_camara_capturando'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='url_stream_isapi',
            field=models.CharField(default='http://{ip}/ISAPI/Streaming/channels/101/picture', help_text='URL de captura ISAPI. Ejemplo: http://{ip}/ISAPI/Streaming/channels/101/picture', max_length=500, verbose_name='URL Stream ISAPI'),
        ),
    ]
