# Generated by Django 5.1.1 on 2026-04-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='Direccion IP')),
                ('puerto', models.IntegerField(help_text='Puerto de conexion (1-65535)', verbose_name='Puerto')),
                ('usuario', models.CharField(blank=True, max_length=50, verbose_name='Usuario de conexion')),
                ('password', models.CharField(blank=True, help_text='Contrasena encriptada', max_length=255, verbose_name='Password de conexion')),
                ('ubicacion_fisica', models.CharField(blank=True, help_text='Ubicacion fisica en el parking', max_length=200, verbose_name='Ubicacion fisica')),
                ('zona_aparcamiento', models.CharField(blank=True, help_text='Zona o area del parking', max_length=100, verbose_name='Zona de aparcamiento')),
                ('resolucion', models.CharField(blank=True, help_text='Resolucion de captura (ej: 1920x1080)', max_length=20, verbose_name='Resolucion')),
                ('url_stream_rtsp', models.CharField(blank=True, help_text='URL del stream RTSP de la camara', max_length=500, verbose_name='URL Stream RTSP')),
                ('estado', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', help_text='Estado de conexion de la camara', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Camara',
                'verbose_name_plural': 'Camaras',
                'ordering': ['nombre'],
            },
        ),
    ]
