# Generated by Django 5.1.1 on 2026-06-05 12:35

from django.db import migrations, models

DEFAULT_ISAPI = 'http://{ip}/ISAPI/Streaming/channels/101/picture'


def backfill_url_stream_isapi(apps, schema_editor):
    Camara = apps.get_model('camaras', 'Camara')
    Camara.objects.filter(url_stream_isapi='').update(url_stream_isapi=DEFAULT_ISAPI)


class Migration(migrations.Migration):

    dependencies = [
        ('camaras', '0004_remove_duplicate_isapi_rename_rtsp'),
    ]

    operations = [
        migrations.RunPython(backfill_url_stream_isapi, migrations.RunPython.noop),
    ]
