# Generated by Django 5.2.16 on 2026-10-01 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espacios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='Direccion IP')),
                ('puerto', models.IntegerField(help_text='Puerto de conexion (1-65535)', verbose_name='Puerto')),
                ('usuario', models.CharField(blank=True, help_text='Usuario para la autenticacion HTTP Digest de la camara', max_length=50, verbose_name='Usuario de conexion')),
                ('password', models.CharField(blank=True, help_text='Se guarda sin cifrar porque la camara exige HTTP Digest, que necesita el valor original. No es una cuenta de usuario.', max_length=255, verbose_name='Password de conexion')),
                ('resolucion', models.CharField(blank=True, help_text='Resolucion de captura (ej: 1920x1080)', max_length=20, verbose_name='Resolucion')),
                ('estado', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', help_text='Estado de conexion de la camara', max_length=20, verbose_name='Estado')),
                ('url_stream_isapi', models.CharField(default='http://{ip}/ISAPI/Streaming/channels/101/picture', help_text='Plantilla de captura. Usa {ip} como marcador.', max_length=500, verbose_name='URL de captura ISAPI')),
                ('espacio_fisico', models.ForeignKey(help_text='Espacio fisico al que pertenece la camara', on_delete=django.db.models.deletion.PROTECT, related_name='camaras', to='espacios.espacio', verbose_name='Espacio')),
            ],
            options={
                'verbose_name': 'Camara',
                'verbose_name_plural': 'Camaras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ControlSistema',
            fields=[
                ('pid', models.PositiveIntegerField(help_text='Identificador del proceso en el sistema operativo', primary_key=True, serialize=False, verbose_name='PID')),
                ('en_ejecucion', models.BooleanField(default=True, verbose_name='En ejecucion')),
                ('inicio', models.DateTimeField(verbose_name='Inicio del proceso')),
                ('camara', models.ForeignKey(help_text='Camara a la que pertenece este proceso', on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='camaras.camara', verbose_name='Camara')),
            ],
            options={
                'verbose_name': 'Control del sistema',
                'verbose_name_plural': 'Controles del sistema',
                'ordering': ['-inicio'],
            },
        ),
    ]
