# Generated by Django 5.2.15 on 2026-08-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('id_usuario', models.IntegerField(blank=True, help_text='Identificador del cliente o propietario', null=True, verbose_name='ID Usuario')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(blank=True, max_length=150, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Direccion')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='Usuario de login')),
                ('password', models.CharField(help_text='Contraseña encriptada', max_length=255, verbose_name='Password')),
                ('nivel_acceso', models.IntegerField(choices=[(1, 'Basico'), (2, 'Administrador')], default=1, help_text='1-Basico, 2-Administrador', verbose_name='Nivel de acceso')),
                ('comentarios', models.TextField(blank=True, help_text='Observaciones adicionales', verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Usuario del Nucleo',
                'verbose_name_plural': 'Usuarios del Nucleo',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
