# Generated by Django 5.2.16 on 2026-09-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='password',
            field=models.CharField(blank=True, help_text='Contraseña encriptada', max_length=255, verbose_name='Password'),
        ),
    ]
