# Generated by Django 5.1.1 on 2026-04-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camaras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de captura')),
                ('ruta_archivo', models.CharField(blank=True, help_text='Ruta del archivo de imagen', max_length=500, verbose_name='Ruta del archivo')),
                ('tamano', models.BigIntegerField(blank=True, null=True, verbose_name='Tamano (bytes)')),
                ('nivel_privacidad', models.CharField(choices=[('publico', 'Publico'), ('privado', 'Privado'), ('confidencial', 'Confidencial')], default='privado', max_length=20, verbose_name='Nivel de privacidad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesada', 'Procesada')], default='pendiente', help_text='Estado de procesamiento', max_length=20, verbose_name='Estado')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios')),
                ('es_referencia', models.BooleanField(default=False, help_text='Imagen usada para inicializar el sistema y crear objetos de referencia', verbose_name='Imagen de referencia')),
                ('camara', models.ForeignKey(blank=True, help_text='Camara que capturo la imagen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes', to='camaras.camara', verbose_name='Camara')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
