# Generated by Django 5.1.1 on 2026-06-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarionucleo',
            name='nivel_acceso',
            field=models.IntegerField(choices=[(1, 'Basico'), (2, 'Administrador')], default=1, help_text='1-Basico, 2-Administrador', verbose_name='Nivel de acceso'),
        ),
    ]
