# Generated by Django 5.1.1 on 2026-04-24 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camaras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicherosDXF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('archivo', models.FileField(help_text='Fichero DXF del parking', upload_to='dxf/', verbose_name='Archivo DXF')),
                ('escala', models.CharField(blank=True, help_text='Escala del plano DXF (ej: 1:100)', max_length=20, verbose_name='Escala')),
                ('unidad_medida', models.CharField(choices=[('metros', 'Metros'), ('centimetros', 'Centimetros')], default='metros', max_length=20, verbose_name='Unidad de medida')),
                ('activo', models.BooleanField(default=False, help_text='Solo un DXF puede estar activo', verbose_name='Activo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado')], default='pendiente', help_text='Estado del procesamiento del DXF', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Fichero DXF',
                'verbose_name_plural': 'Ficheros DXF',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('tag', models.CharField(blank=True, help_text='Etiqueta manual para la zona', max_length=50, verbose_name='Tag')),
                ('coordenadas_posicion', models.CharField(blank=True, help_text='Coordenadas X, Y de posicion', max_length=100, verbose_name='Coordenadas de posicion')),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ancho (metros)')),
                ('largo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Largo (metros)')),
                ('rotacion', models.DecimalField(decimal_places=2, default=0, help_text='Angulo de rotacion (0-360 grados)', max_digits=5, verbose_name='Rotacion (grados)')),
                ('centroide', models.CharField(blank=True, help_text='Coordenadas del centroide (Xc, Yc)', max_length=50, verbose_name='Centroide')),
                ('vertices', models.JSONField(blank=True, help_text='Coordenadas del poligono de la zona', null=True, verbose_name='Vertices del poligono')),
                ('camara_asignada', models.ForeignKey(blank=True, help_text='Camara asignada para supervisar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas', to='camaras.camara', verbose_name='Camara asignada')),
                ('dxf_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zonas', to='zonas.ficherosdxf', verbose_name='DXF de origen')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['tipo', 'nombre'],
            },
        ),
    ]
